// BHARATSCALES — Shared resource/blog content
// Keyed by slug (used in blog.html?slug=slug)
window.BLOGS = {
  'downtime-case-study': {
    type: 'Case study',
    title: 'How a manufacturer cut unplanned downtime by 50%',
    excerpt: 'A mid-sized automotive parts maker connected its machines, surfaced early warning signals, and turned firefighting into planned maintenance.',
    image: 'assets/resource-case-study.png',
    imageAlt: 'Automated robotic arms working on a vehicle assembly line',
    date: 'June 10, 2026',
    readTime: '6 min read',
    author: 'BHARATSCALES Team',
    content: [
      { type: 'p', text: 'Unplanned downtime is one of the most expensive problems on any factory floor. Every unexpected stop ripples through production schedules, delivery commitments, and margins. For one mid-sized automotive parts manufacturer, downtime had become the single biggest threat to on-time delivery — until they changed how they used their data.' },
      { type: 'h2', text: 'The challenge' },
      { type: 'p', text: 'The plant ran dozens of CNC machines, presses, and conveyors across three shifts. Maintenance was almost entirely reactive: a machine failed, an alarm went off, and the team scrambled to fix it. Critical data lived in disconnected systems — the PLCs on the floor, spreadsheets in the maintenance office, and an ERP that nobody on the line ever opened.' },
      { type: 'list', items: [
        'Frequent, unpredictable machine stoppages during peak production',
        'No early visibility into developing faults before they became failures',
        'Maintenance data scattered across PLCs, spreadsheets, and the ERP',
        'Operators and managers working from different versions of the truth',
      ] },
      { type: 'h2', text: 'What we did' },
      { type: 'p', text: 'BHARATSCALES connected the plant\u2019s existing machines to a single platform — no rip-and-replace. We tapped into the controllers already on the floor, streamed sensor data to the edge, and brought IT, OT, and edge signals together into one live view.' },
      { type: 'p', text: 'On top of that unified data, our AI models learned the normal operating signature of each machine. When vibration, temperature, or cycle-time patterns started to drift, the system flagged it — days before a breakdown — and routed the alert to the right technician with a recommended action.' },
      { type: 'quote', text: 'For the first time, we were fixing machines on our schedule, not theirs. The team stopped firefighting and started planning.', cite: 'Plant Maintenance Head' },
      { type: 'h2', text: 'The results' },
      { type: 'p', text: 'Within four months of going live, the plant saw measurable, sustained improvement across the metrics that mattered most.' },
      { type: 'stats', items: [
        { num: '50%', label: 'Reduction in unplanned downtime' },
        { num: '32%', label: 'Faster mean time to repair' },
        { num: '18%', label: 'Increase in overall throughput' },
      ] },
      { type: 'h2', text: 'Why it worked' },
      { type: 'p', text: 'The breakthrough was not a single sensor or a clever algorithm. It was connecting data that already existed and putting clear, timely signals in front of the people who could act on them. Predictive maintenance only pays off when insights reach the floor in time — and in a form a technician can trust and use.' },
      { type: 'p', text: 'Today the plant runs a rolling maintenance schedule driven by machine health, not the calendar. Spare parts are ordered ahead of need, shifts are planned around real capacity, and the late-night emergency call has become the exception rather than the rule.' },
    ],
  },

  'it-ot-edge-playbook': {
    type: 'White paper',
    title: 'Connecting IT, OT & edge: an industrial AI playbook',
    excerpt: 'A practical framework for unifying enterprise, operational, and edge data so AI can deliver outcomes on the factory floor.',
    image: 'assets/resource-white-paper.png',
    imageAlt: 'Connected industrial systems and data networks',
    date: 'June 4, 2026',
    readTime: '8 min read',
    author: 'BHARATSCALES Team',
    content: [
      { type: 'p', text: 'Most industrial AI projects do not fail because the models are bad. They fail because the data never comes together. Enterprise systems, operational technology, and edge devices each speak their own language, and bridging them is the real work behind any successful deployment.' },
      { type: 'h2', text: 'Three worlds, one operation' },
      { type: 'p', text: 'Every plant lives across three layers. Each holds part of the picture, and none of them is complete on its own.' },
      { type: 'list', items: [
        'IT — ERP, MES, and business systems that track orders, inventory, and cost',
        'OT — PLCs, SCADA, and control systems that run the physical process',
        'Edge — sensors and gateways that capture high-frequency signals in real time',
      ] },
      { type: 'p', text: 'Value appears when these layers are joined: a quality dip on the line (OT) linked to a specific batch of raw material (IT) and a temperature spike from a sensor (edge). No single system can tell that story alone.' },
      { type: 'h2', text: 'The playbook' },
      { type: 'p', text: 'We follow a repeatable sequence that gets teams from scattered data to real outcomes without a multi-year transformation program.' },
      { type: 'list', items: [
        'Connect first — tap existing controllers and systems instead of replacing them',
        'Unify the model — map every signal to a common, contextual data structure',
        'Stream to the edge — process time-sensitive data where it is generated',
        'Apply AI where it pays — start with the highest-cost, highest-frequency problem',
        'Close the loop — push insights back to operators and systems that can act',
      ] },
      { type: 'quote', text: 'The goal is not a dashboard. The goal is a decision, made faster, by the right person or system.', cite: 'BHARATSCALES Engineering' },
      { type: 'h2', text: 'Common pitfalls to avoid' },
      { type: 'list', items: [
        'Boiling the ocean — connecting everything before proving value anywhere',
        'Ignoring the edge — sending raw high-frequency data to the cloud and paying for it twice',
        'Leaving operators out — insights that never reach the floor change nothing',
        'Treating security as an afterthought in the IT/OT bridge',
      ] },
      { type: 'h2', text: 'Where to start' },
      { type: 'p', text: 'Pick one expensive, recurring problem — unplanned downtime, scrap, energy waste — and connect only the data needed to solve it. Prove the outcome, then expand. Industrial AI scales best when each step pays for the next.' },
    ],
  },

  'predictive-maintenance-overview': {
    type: 'Data sheet',
    title: 'IoT predictive maintenance: platform overview',
    excerpt: 'How the BHARATSCALES platform turns raw sensor data into early failure warnings and planned maintenance action.',
    image: 'assets/resource-data-sheet.png',
    imageAlt: 'IoT sensors and predictive maintenance monitoring',
    date: 'May 28, 2026',
    readTime: '5 min read',
    author: 'BHARATSCALES Team',
    content: [
      { type: 'p', text: 'BHARATSCALES predictive maintenance combines IoT connectivity, edge processing, and AI to detect developing faults before they cause failures. This overview covers how the platform fits into your operation and what it delivers.' },
      { type: 'h2', text: 'How it works' },
      { type: 'list', items: [
        'Connect — stream data from existing sensors, PLCs, and controllers',
        'Monitor — build a live health profile for every critical asset',
        'Predict — AI models detect drift and anomalies days before failure',
        'Act — alerts reach the right technician with a recommended fix',
      ] },
      { type: 'h2', text: 'Key capabilities' },
      { type: 'list', items: [
        'Vibration, temperature, current, and cycle-time monitoring',
        'Edge processing for low-latency, bandwidth-efficient analysis',
        'Self-learning baselines that adapt to each machine',
        'Configurable alerts via dashboard, email, and mobile',
        'Open APIs to push events into your ERP, CMMS, or MES',
      ] },
      { type: 'h2', text: 'What it delivers' },
      { type: 'stats', items: [
        { num: '40%', label: 'Typical reduction in downtime' },
        { num: '25%', label: 'Lower maintenance cost' },
        { num: '99%', label: 'Platform uptime' },
      ] },
      { type: 'h2', text: 'Deployment' },
      { type: 'p', text: 'The platform is designed to layer onto existing equipment with no rip-and-replace. Most sites are connected and surfacing their first insights within weeks, starting with the most critical assets and expanding from there.' },
      { type: 'quote', text: 'Predictive maintenance only works when the warning arrives in time to act. That is what we build for.', cite: 'BHARATSCALES Engineering' },
    ],
  },
};
