// BHARATSCALES — Shared job openings data
// Keyed by slug (used in job.html?role=slug)
window.JOBS = {
  'sde-intern': {
    title: 'SDE Intern',
    category: 'Technology',
    location: 'Kanpur, India',
    type: 'Internship',
    datePosted: '11/06/2026',
    travel: 'No',
    experience: 'Students / freshers',
    intro: 'BHARATSCALES builds AI automation software and IoT solutions for India\u2019s industries. As an SDE Intern, you\u2019ll work alongside our engineering team on real production features that connect IT, OT, and edge data on the factory floor.',
    responsibilities: [
      'Build and test features across our web platform and internal tools',
      'Write clean, well-documented code and participate in code reviews',
      'Help debug issues and improve performance of existing services',
      'Collaborate with senior engineers, designers, and product teammates',
      'Learn our stack and contribute to real deployments, not toy projects',
    ],
    requirements: [
      'Pursuing or recently completed a degree in CS, IT, or related field',
      'Solid fundamentals in data structures, algorithms, and at least one language (Python, JavaScript, Java, or C++)',
      'Familiarity with Git and basic web concepts (HTTP, REST APIs)',
      'Eagerness to learn, take feedback, and ship',
      'Bonus: exposure to React, Node.js, Python, or IoT/embedded systems',
    ],
    benefits: [
      'Mentorship from experienced engineers',
      'Work on production AI & IoT at scale',
      'Stipend and a path to a full-time offer',
      'Flexible, collaborative work culture',
    ],
  },
  'business-developer': {
    title: 'Business Developer',
    category: 'Sales & Growth',
    location: 'Kanpur, India',
    type: 'Full-time',
    datePosted: '11/06/2026',
    travel: 'Occasional',
    experience: '1+ years experience',
    intro: 'We\u2019re looking for a driven Business Developer to grow BHARATSCALES\u2019 footprint across India\u2019s industrial sector. You\u2019ll identify opportunities, build relationships with manufacturers, and help bring AI automation and IoT to the shop floor.',
    responsibilities: [
      'Identify, qualify, and pursue new business opportunities',
      'Build and maintain relationships with industrial clients and partners',
      'Understand customer needs and map them to our solutions',
      'Prepare proposals, pitches, and product demos with the team',
      'Track pipeline, hit targets, and report on progress',
    ],
    requirements: [
      '1+ years in business development, sales, or a client-facing role',
      'Excellent communication and negotiation skills',
      'Ability to understand technical products and explain them simply',
      'Self-starter who thrives on targets and ownership',
      'Bonus: experience selling to manufacturing or industrial customers',
    ],
    benefits: [
      'Competitive pay with performance incentives',
      'Direct impact on company growth',
      'Learning budget & mentorship',
      'Fast-growth environment with room to lead',
    ],
  },
  'fullstack-python-developer': {
    title: 'Full-Stack Python Developer',
    category: 'Technology',
    location: 'Kanpur, India',
    type: 'Full-time',
    datePosted: '11/06/2026',
    travel: 'No',
    experience: '1+ years experience',
    intro: 'Join BHARATSCALES as a Full-Stack Python Developer and help build the platform powering industrial AI and IoT. You\u2019ll work across the stack \u2014 from APIs and data pipelines to clean, responsive front-ends.',
    responsibilities: [
      'Design, build, and maintain backend services and APIs in Python',
      'Develop responsive front-end interfaces and dashboards',
      'Work with databases, data pipelines, and IoT data streams',
      'Write tests, review code, and ship reliable features',
      'Collaborate with the team on architecture and product decisions',
    ],
    requirements: [
      '1+ years building full-stack applications',
      'Strong Python skills (Django, Flask, or FastAPI)',
      'Front-end experience with JavaScript and a modern framework (React preferred)',
      'Comfortable with SQL/NoSQL databases and REST APIs',
      'Bonus: experience with cloud, Docker, or IoT/real-time data',
    ],
    benefits: [
      'Work on production AI & IoT at scale',
      'Competitive pay and growth opportunities',
      'Learning budget & mentorship',
      'Collaborative, engineering-first culture',
    ],
  },
};
